name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установка Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Укажите вашу версию Go

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: go mod tidy

      # Шаг 4: Запуск статического анализа
      - name: Run linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run

      # Шаг 5: Сборка приложения
      - name: Build application
        run: go build -o app .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
              echo "Deploying to production server..."
            # Здесь может быть ваш скрипт деплоя.

